"""update user fields

Revision ID: e218137189bb
Revises: 45e1b0180326
Create Date: 2026-06-12 09:59:22.928168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e218137189bb'
down_revision: Union[str, Sequence[str], None] = '45e1b0180326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('tb_users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('tb_users', sa.Column('birth_date', sa.Date(), nullable=False))
    op.drop_column('tb_users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tb_users', 'birth_date')
    op.drop_column('tb_users', 'last_name')
    op.drop_column('tb_users', 'first_name')
    # ### end Alembic commands ###
